
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - moodle_code:/var/www/html        # 👈 same volume  
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - web_network

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - moodle_code:/var/www/html        # 👈 shared volume
      - ./moodledata:/var/www/moodledata
    networks:
      - web_network

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - web_network

  
# Optional Moodle container (only if you want a separate Moodle service)
#  moodle:
#    container_name: moodle
#    build:
#      context: ./moodle
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#        - ./moodle/html:/var/www/html
#        - ./moodle/moodledata:/var/www/moodledata
#    networks:
#        - web_network


networks:
    web_network:
     #external: true   # This tells Docker to use the existing network on the host
     driver: bridge    # This ensures all containers are on the same network

volumes:
    mysql_data:
    moodledata:
    moodle_code:  
