version: '3.8'

services:
  nginx:
    image: custom-nginx:1.21.4
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./moodle/html:/var/www/html      # Serve Moodle code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - web_network


  php-fpm:
    image: custom-php:8.3
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./moodle/html:/var/www/html             # Moodle code for PHP
      - ./moodle/moodledata:/var/www/moodledata
    networks:
      - web_network


  mysql:
    image: mysql:8.0
    env_file:
        - .env.sql         # This loads the environment variables
    volumes:
        - ./mysql/mysql-data:/var/lib/mysql                      # Persistent MySQL data
    networks:
        - web_network

  
# Optional Moodle container (only if you want a separate Moodle service)
#  moodle:
#    container_name: moodle
#    build:
#      context: ./moodle
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#        - ./moodle/html:/var/www/html
#        - ./moodle/moodledata:/var/www/moodledata
#    networks:
#        - web_network


networks:
    web_network:
     #external: true   # This tells Docker to use the existing network on the host
     driver: bridge    # This ensures all containers are on the same network


