apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/moodle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
