# php deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      initContainers:
        - name: init-moodle
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              set -e

              echo "Installing init-container tools..."
              apk add --no-cache wget tar
              echo "Tools installed."

              cd /var/www/html

              if [ ! -f index.php ]; then
                echo "Moodle files not found. Downloading Moodle..."

                wget --max-redirect=5 -O moodle.tgz "https://download.moodle.org/download.php/direct/stable404/moodle-latest-404.tgz"

                echo "Moodle download complete."

                echo "Extracting Moodle archive..."
                tar -xzf moodle.tgz
                echo "Moodle archive extracted."

                echo "Copying Moodle application files..."
                cp -a moodle/. .
                echo "Moodle application files copied."

                echo "Cleaning up Moodle installation files..."
                rm -rf moodle moodle.tgz
                echo "Moodle installation files cleaned up."
              else
                echo "Existing Moodle application files found. Skipping download and extraction."
              fi

              echo "Setting ownership on /var/www/html..."
              chown -R 33:33 /var/www/html
              echo "/var/www/html ownership complete."

              echo "Setting ownership on /moodledata..."
              chown -R 33:33 /moodledata
              echo "/moodledata ownership complete."

              echo "Moodle init container completed successfully."
          volumeMounts:
            - name: moodle-code
              mountPath: /var/www/html
            - name: moodle-data
              mountPath: /moodledata
      containers:
      - name: php
        image: northamerica-northeast2-docker.pkg.dev/civic-champion-439320-a5/moodle-repo/custom-php:8.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: moodle
        - name: DB_USER
          value: moodleuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-secret
              key: db-password
        volumeMounts:
        - name: moodle-code
          mountPath: /var/www/html
        - name: moodle-data
          mountPath: /moodledata
      volumes:
      - name: moodle-code
        persistentVolumeClaim:
          claimName: moodle-pvc
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodledata-pvc
