apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../storage
  - ../../mysql
  - ../../php
  - ../../nginx
  - ./ingress.yaml

images:
  - name: php
    newName: extn-php
    newTag: "8.2"
