apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /var/www/html;

        # Health check endpoint
        location = /healthz {
            access_log off;
            default_type text/plain;
            return 200 "OK\n";
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php(/|$) {
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php:9000; # Points to your independent PHP service
            
            # TWO TIMEOUT LINES 
            fastcgi_read_timeout 600s;
            fastcgi_send_timeout 600s;

            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTP_PROXY "";

            # CRITICAL FOR HTTPS TRANSLATION IN MOODLE
            fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
            
            # THESE TWO LINES FOR REAL IP PASS-THROUGH
            fastcgi_param HTTP_X_REAL_IP $remote_addr;
            fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        }
    }