name: Deploy Moodle to EKS

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: civic-champion-439320-a5
  REGION: northamerica-northeast2
  CLUSTER_NAME: moodle-gke-cluster
  CLUSTER_LOCATION: northamerica-northeast2-a
  IMAGE: northamerica-northeast2-docker.pkg.dev/civic-champion-439320-a5/moodle-repo/custom-php:8.2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
